version : "3"
services:
  azuretablesapi_prod:
    container_name: azuretablesapi_dev
    image: azuretablesapi_dev:latest
    ports:
      - "3000:3000"    
    build:       
      context: .
      args:
        - NODE_ENV=development        
    volumes:
      # :ro to keep this folder readonly so that docker cannot write anything back to source
      - ./:/app:ro
      # this folder to be retained 
      - /app/node_modules 
    environment:
      - PORT=3000
      - NODE_ENV=development # in prod set it to prod      
    # env_file: 
    #   - ./.env
    command: npm run dev