version : "3"
services:
  azuretablesapi_prod:    
    container_name: azuretablesapi_prod
    image: azuretablesapi_prod:latest
    ports:
      - "4000:4000"    
    build:       
      context: .
      args:
        - NODE_ENV=production
    environment:
      - PORT=4000
      - NODE_ENV=production # in prod set it to prod
    # env_file: 
    #   - ./.env
    command: npm start